import { type NextPage } from "next";
import { SignIn, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import Image from "next/image";

import folder from "../assets/folder.png";
import addfolder from "../assets/add-folder.png";

import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton,
} from "@clerk/nextjs";

const CreateProject: NextPage = () => {
  return (
    <div>
      <input type="text"></input>
    </div>
  );
};

const Home: NextPage = () => {
  const { data, isLoading } = api.projects.getAll.useQuery();

  if (isLoading)
    return (
      <div className="flex h-screen justify-center align-middle">
        Loading...
      </div>
    );

  if (!data)
    return (
      <div className="flex h-screen justify-center align-middle">
        Something went wrong
      </div>
    );

  return (
    <>
      <Head>
        <title>Mix Notes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex items-center justify-between border-b border-slate-400 bg-scampi-950 p-4">
        <p>MIX NOTES</p>
        <SignedIn>
          {/* Mount the UserButton component */}
          <UserButton afterSignOutUrl="/" />
        </SignedIn>
        <SignedOut>
          {/* Signed out users get sign in button */}
          <SignInButton />
        </SignedOut>
      </header>

      <main className="flex h-screen justify-center">
        <div className="w-full md:max-w-5xl">
          <div className="flex flex-col pt-4">
            {/* <CreateProject /> */}
            {data?.map((project) => (
              <article
                className="mt-4 flex items-center gap-3 rounded border border-scampi-300 p-4 transition duration-500 ease-out hover:bg-scampi-950 "
                key={project.id}
              >
                <Image
                  src={folder}
                  height={20}
                  width={20}
                  alt="folder picture"
                />
                <span>{project.name}</span>
              </article>
            ))}
            <article className="mt-4 flex items-center justify-center gap-3 rounded border border-scampi-600 bg-scampi-950 p-4 transition duration-500 ease-out hover:bg-scampi-900">
              <Image
                src={addfolder}
                height={20}
                width={20}
                alt="add folder picture"
              />
            </article>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
